name: "rynopay_client_site_prod_pipeline"
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  #ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: prod_website                 # set this to your Amazon ECS service name
  ECS_CLUSTER: Rynopay_Website                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .aws/task-definition.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: website           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  build-push-image-to-ECR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials #This credential should have ECS permissions
      uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      with:
        aws-access-key-id: ${{ secrets.ECR_IAM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_IAM_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to ECR
      id: ecr_login
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.us-east-1.amazonaws.com
        username: ${{ secrets.ECR_IAM_ACCESS_KEY_ID }}
        password: ${{ secrets.ECR_IAM_SECRET_ACCESS_KEY }}

    - name: Build and push to ECR
      id: docker_build
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.us-east-1.amazonaws.com/rynopay_prod/client_site:${{ github.sha }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.us-east-1.amazonaws.com/rynopay_prod/client_site:${{ github.sha }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true